from figures.Point2D import Point2D
from figures.Figure import Figure
from figures.Rectangle import Rectangle
from figures.Square import Square
from figures.Ellipse import Ellipse
from figures.Circle import Circle
from figures.Triangle import Triangle
from figures.Rhombus import Rhombus
from figures.Segment import Segment
from figures.Ray import Ray
from figures.Line import Line
